# Generated by Django 5.2.6 on 2025-09-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('age', models.IntegerField(default=18)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('YesNo', models.BooleanField()),
                ('hobby', models.CharField(blank=True)),
            ],
        ),
    ]
